### ISSUE TITLE
Don't print info messages from requests library 

### ISSUE THREAD

**Issue by eleweek** [eleweek/SearchingReddit#3]
Basically do what I failed in the 4th episode(http://www.youtube.com/watch?v=rkb-Gh-lc3E&index=5&list=PL18yrUuMk-zlzpea3En7GRZLvFn7WNK0H)

info messages from requests lib => not ok
info messages from other modules => ok

**Comment by ChChCheeeeo** [comment]
Adding logging.getLogger("requests").setLevel(logging.WARNING) to cralwer supresses request info messages.

**Comment by eleweek** [comment]
Thank you for contributing!
